# -----------------------------------------------------
# Monitor Setup
# name: "Default"
# -----------------------------------------------------

monitor=,preferred,auto,1.333333

# Fixes blurred applications on HiDPI displays
xwayland { 
    force_zero_scaling = true 
    } 